In [1]:
import pandas as pd
import numpy as np

### DataFrame Basics

In [2]:
# Crate DF from file 
retails_df = pd.read_csv("../retail/retail_2016_2017.csv")
print(retails_df)

              id        date  store_nbr                      family     sales  \
0        1945944  2016-01-01          1                  AUTOMOTIVE     0.000
1        1945945  2016-01-01          1                   BABY CARE     0.000
2        1945946  2016-01-01          1                      BEAUTY     0.000
3        1945947  2016-01-01          1                   BEVERAGES     0.000
4        1945948  2016-01-01          1                       BOOKS     0.000
...          ...         ...        ...                         ...       ...
1054939  3000883  2017-08-15          9                     POULTRY   438.133
1054940  3000884  2017-08-15          9              PREPARED FOODS   154.553
1054941  3000885  2017-08-15          9                     PRODUCE  2419.729
1054942  3000886  2017-08-15          9  SCHOOL AND OFFICE SUPPLIES   121.000
1054943  3000887  2017-08-15          9                     SEAFOOD    16.000

         onpromotion
0                  0
1                  0
2                  0
3                  0
4                  0
...              ...
1054939            0
1054940            1
1054941          148
1054942            8
1054943            0

[1054944 rows x 6 columns]

In [3]:
# Crate DF from file 
oil_df = pd.read_csv("../retail/oil.csv")
print(oil_df)

            date  dcoilwtico
0     2013-01-01         NaN
1     2013-01-02       93.14
2     2013-01-03       92.97
3     2013-01-04       93.12
4     2013-01-07       93.20
...          ...         ...
1213  2017-08-25       47.65
1214  2017-08-28       46.40
1215  2017-08-29       46.46
1216  2017-08-30       45.96
1217  2017-08-31       47.26

[1218 rows x 2 columns]

In [4]:
oil_df.shape # Shape

(1218, 2)

In [6]:
oil_df.index # Index info

RangeIndex(start=0, stop=1218, step=1)

In [7]:
oil_df.columns # Index column

Index(['date', 'dcoilwtico'], dtype='str')

In [8]:
oil_df.head(3) #

         date  dcoilwtico
0  2013-01-01         NaN
1  2013-01-02       93.14
2  2013-01-03       92.97

In [9]:
oil_df.tail(3) #

            date  dcoilwtico
1215  2017-08-29       46.46
1216  2017-08-30       45.96
1217  2017-08-31       47.26

In [10]:
oil_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1218 entries, 0 to 1217
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1218 non-null   str
 1   dcoilwtico  1175 non-null   float64
dtypes: float64(1), str(1)
memory usage: 19.2 KB

In [11]:
# Crate DF from python Dict
dict= {"id": [1,2], "name": ["abc","xyz"]}
myPd = pd.DataFrame(dict)
print(myPd)

   id name
0   1  abc
1   2  xyz

# Assignment 1: DataFrame Basics

Hi there!

Can you read in the transactions dataset and report on:

* The number of rows and columns
* The names of the columns
* The datatypes of each column

In [12]:
# A common practice is to create a path variable to pass to read_csv
path = "../retail/transactions.csv"

# read in trasactions csv and create DataFrame
transactions = pd.read_csv(path)

# return DataFrame (df)
transactions

             date  store_nbr  transactions
0      2013-01-01         25           770
1      2013-01-02          1          2111
2      2013-01-02          2          2358
3      2013-01-02          3          3487
4      2013-01-02          4          1922
...           ...        ...           ...
83483  2017-08-15         50          2804
83484  2017-08-15         51          1573
83485  2017-08-15         52          2255
83486  2017-08-15         53           932
83487  2017-08-15         54           802

[83488 rows x 3 columns]

In [13]:
# shape of df: 84388 rows, 3 columns (not including index)
transactions.shape

(83488, 3)

In [14]:
# shape of df: 84388 rows. Add 1 to max default index value to get row count
transactions.index.max() + 1

83488

In [15]:
# dtypes attribute returns column names and their data types
transactions.dtypes

date              str
store_nbr       int64
transactions    int64
dtype: object

In [16]:
transactions.info()

<class 'pandas.DataFrame'>
RangeIndex: 83488 entries, 0 to 83487
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   date          83488 non-null  str
 1   store_nbr     83488 non-null  int64
 2   transactions  83488 non-null  int64
dtypes: int64(2), str(1)
memory usage: 1.9 MB

# Assignment 2: Exploring DataFrames

Hello!

* Can you quickly inspect the first 5 rows of the transactions data? 

* Then, dive a bit more deeply into the data and check if there are any missing values.
* What about the number of unique dates? I want to make sure we didn’t leave any out.
* Finally, can you report the mean, median, min and max of “transactions”?  I want to check for any anomalies in our data.

In [17]:
# Look at top 5 rows with .head()
transactions.head()

         date  store_nbr  transactions
0  2013-01-01         25           770
1  2013-01-02          1          2111
2  2013-01-02          2          2358
3  2013-01-02          3          3487
4  2013-01-02          4          1922

In [18]:
# use .isna().sum() on df to get missing counts for all columns

transactions.isna().sum()

date            0
store_nbr       0
transactions    0
dtype: int64

In [19]:
# Use info to determine missing counts - none are missing!
transactions.info()

<class 'pandas.DataFrame'>
RangeIndex: 83488 entries, 0 to 83487
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   date          83488 non-null  str
 1   store_nbr     83488 non-null  int64
 2   transactions  83488 non-null  int64
dtypes: int64(2), str(1)
memory usage: 1.9 MB

In [20]:
# Use describe to return the specified aggregations (and more!)
transactions.describe()

          store_nbr  transactions
count  83488.000000  83488.000000
mean      26.939237   1694.602158
std       15.608204    963.286644
min        1.000000      5.000000
25%       13.000000   1046.000000
50%       27.000000   1393.000000
75%       40.000000   2079.000000
max       54.000000   8359.000000

In [21]:
# Method 1 for unique dates - once you know how to access columns :D
transactions["date"].nunique()

1682

In [22]:
# Method 2 for unique dates - speecify include="all" to get stats on text columns.

transactions.describe(include="all")

              date     store_nbr  transactions
count        83488  83488.000000  83488.000000
unique        1682           NaN           NaN
top     2017-04-20           NaN           NaN
freq            54           NaN           NaN
mean           NaN     26.939237   1694.602158
std            NaN     15.608204    963.286644
min            NaN      1.000000      5.000000
25%            NaN     13.000000   1046.000000
50%            NaN     27.000000   1393.000000
75%            NaN     40.000000   2079.000000
max            NaN     54.000000   8359.000000

### Accessing DataFrames

In [23]:
oil = pd.read_csv("../retail/oil.csv")

In [24]:
oil.columns = ["date", "price"]

In [25]:
oil[["price"]]

      price
0       NaN
1     93.14
2     92.97
3     93.12
4     93.20
...     ...
1213  47.65
1214  46.40
1215  46.46
1216  45.96
1217  47.26

[1218 rows x 1 columns]

In [26]:
oil.iloc[2] # get by index

date     2013-01-03
price         92.97
Name: 2, dtype: object

In [27]:
retails_df.iloc[:,1:4] # get by index All raws 2-4 coloums

               date  store_nbr                      family
0        2016-01-01          1                  AUTOMOTIVE
1        2016-01-01          1                   BABY CARE
2        2016-01-01          1                      BEAUTY
3        2016-01-01          1                   BEVERAGES
4        2016-01-01          1                       BOOKS
...             ...        ...                         ...
1054939  2017-08-15          9                     POULTRY
1054940  2017-08-15          9              PREPARED FOODS
1054941  2017-08-15          9                     PRODUCE
1054942  2017-08-15          9  SCHOOL AND OFFICE SUPPLIES
1054943  2017-08-15          9                     SEAFOOD

[1054944 rows x 3 columns]

In [28]:
retails_df.iloc[:5,1:4] # get by index# firsxt 5  raws 2-4 coloums

         date  store_nbr      family
0  2016-01-01          1  AUTOMOTIVE
1  2016-01-01          1   BABY CARE
2  2016-01-01          1      BEAUTY
3  2016-01-01          1   BEVERAGES
4  2016-01-01          1       BOOKS

In [29]:
retails_df.loc[:, "date"] #W first Parameter rows(all rows), second access coloums
retails_df.loc[:, ["date", "sales"]] #W first Parameter rows, second access coloums

               date     sales
0        2016-01-01     0.000
1        2016-01-01     0.000
2        2016-01-01     0.000
3        2016-01-01     0.000
4        2016-01-01     0.000
...             ...       ...
1054939  2017-08-15   438.133
1054940  2017-08-15   154.553
1054941  2017-08-15  2419.729
1054942  2017-08-15   121.000
1054943  2017-08-15    16.000

[1054944 rows x 2 columns]

In [30]:
retails_df.loc[:, "date"] #W first Parameter rows, second access coloums

0          2016-01-01
1          2016-01-01
2          2016-01-01
3          2016-01-01
4          2016-01-01
              ...
1054939    2017-08-15
1054940    2017-08-15
1054941    2017-08-15
1054942    2017-08-15
1054943    2017-08-15
Name: date, Length: 1054944, dtype: str

# Exercise 3 - Accessing DataFrames

Hi, starting to dive deeper into this data.

I noticed that the first row is the only one from 2013-01-01.

* Can you get me a copy of the DataFrame that excludes that row, and only includes “store_nbr” and “transactions”?
* Also, can you report the number of unique store numbers?
* Finally, return the total number of transactions in millions

In [31]:
transactions.head()

         date  store_nbr  transactions
0  2013-01-01         25           770
1  2013-01-02          1          2111
2  2013-01-02          2          2358
3  2013-01-02          3          3487
4  2013-01-02          4          1922

In [32]:
# skip the first row via slicing

transactions.loc[1:, "store_nbr":"transactions"]

       store_nbr  transactions
1              1          2111
2              2          2358
3              3          3487
4              4          1922
5              5          1903
...          ...           ...
83483         50          2804
83484         51          1573
83485         52          2255
83486         53           932
83487         54           802

[83487 rows x 2 columns]

In [33]:
# calculate sum of store number column

transactions.loc[:, "store_nbr"].nunique()

54

In [34]:
# Divide sum of transactions by millions to get in units of millions

transactions.loc[:, "transactions"].sum() / 1000000

np.float64(141.478945)

### Dropping Data and Duplicates

In [35]:
retails_df

,id,date,store_nbr,family,sales,onpromotion
0,1945944,2016-01-01,1,AUTOMOTIVE,0.000,0
1,1945945,2016-01-01,1,BABY CARE,0.000,0
2,1945946,2016-01-01,1,BEAUTY,0.000,0
3,1945947,2016-01-01,1,BEVERAGES,0.000,0
4,1945948,2016-01-01,1,BOOKS,0.000,0
...,...,...,...,...,...,...
1054939,3000883,2017-08-15,9,POULTRY,438.133,0
1054940,3000884,2017-08-15,9,PREPARED FOODS,154.553,1
1054941,3000885,2017-08-15,9,PRODUCE,2419.729,148
1054942,3000886,2017-08-15,9,SCHOOL AND OFFICE SUPPLIES,121.000,8
1054943,3000887,2017-08-15,9,SEAFOOD,16.000,0

In [36]:
# Axis = 0 drop rows and axis=1 drop columns
retails_df.drop("id", axis=1).head() 
#retails_df.drop(["id]", inplace=True, axis=1) # PERMNATLY REMOVE

         date  store_nbr      family  sales  onpromotion
0  2016-01-01          1  AUTOMOTIVE    0.0            0
1  2016-01-01          1   BABY CARE    0.0            0
2  2016-01-01          1      BEAUTY    0.0            0
3  2016-01-01          1   BEVERAGES    0.0            0
4  2016-01-01          1       BOOKS    0.0            0

In [37]:
retails_df.head()

        id        date  store_nbr      family  sales  onpromotion
0  1945944  2016-01-01          1  AUTOMOTIVE    0.0            0
1  1945945  2016-01-01          1   BABY CARE    0.0            0
2  1945946  2016-01-01          1      BEAUTY    0.0            0
3  1945947  2016-01-01          1   BEVERAGES    0.0            0
4  1945948  2016-01-01          1       BOOKS    0.0            0

In [38]:
path = "../project_data/product.csv"

# read in trasactions csv and create DataFrame
product_df = pd.read_csv(path)
product_df
product_df.duplicated()
#product_df.drop_duplicates(subset="product", keep="last") # Delete duplicate

0        False
1        False
2        False
3        False
4        False
         ...
92348    False
92349    False
92350    False
92351    False
92352    False
Length: 92353, dtype: bool

# Assignment 4: Dropping Data and Duplicates

Hi there!

Can you:

1. Drop the first row of data? We want it permanently removed. 
2. Drop the date column but not in place
3. Return a dataframe that only includes the last row for each of the stores.

Thanks!

In [39]:
transactions.head()

         date  store_nbr  transactions
0  2013-01-01         25           770
1  2013-01-02          1          2111
2  2013-01-02          2          2358
3  2013-01-02          3          3487
4  2013-01-02          4          1922

In [40]:
# drop the first row of data in place

transactions.drop(0, axis=0, inplace=True)

transactions

             date  store_nbr  transactions
1      2013-01-02          1          2111
2      2013-01-02          2          2358
3      2013-01-02          3          3487
4      2013-01-02          4          1922
5      2013-01-02          5          1903
...           ...        ...           ...
83483  2017-08-15         50          2804
83484  2017-08-15         51          1573
83485  2017-08-15         52          2255
83486  2017-08-15         53           932
83487  2017-08-15         54           802

[83487 rows x 3 columns]

In [41]:
# drop date but not in place

transactions.drop("date", axis=1)

       store_nbr  transactions
1              1          2111
2              2          2358
3              3          3487
4              4          1922
5              5          1903
...          ...           ...
83483         50          2804
83484         51          1573
83485         52          2255
83486         53           932
83487         54           802

[83487 rows x 2 columns]

In [42]:
# drop duplicate rows subsetting by store number. keep last entry for each store

transactions.drop_duplicates(subset="store_nbr", keep="last").head()

             date  store_nbr  transactions
83434  2017-08-15          1          1693
83435  2017-08-15          2          1737
83436  2017-08-15          3          2956
83437  2017-08-15          4          1283
83438  2017-08-15          5          1310

# Assignment 5: Missing Data

Hello, 

Can you tell if any dates or prices are missing in the oil dataset?

Then compare the mean of the oil series when filling in with mean vs. filling in with 0.

Thanks!

In [43]:
oil = pd.read_csv("../retail/oil.csv")

In [44]:
# info can be used to infer missing counts 1218 - 1175 = 43

oil.info()

<class 'pandas.DataFrame'>
RangeIndex: 1218 entries, 0 to 1217
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1218 non-null   str
 1   dcoilwtico  1175 non-null   float64
dtypes: float64(1), str(1)
memory usage: 19.2 KB

In [45]:
# But usually easier to use isna().sum() - let the computer count for you :D

oil.isna().sum()

date           0
dcoilwtico    43
dtype: int64

In [46]:
# calculate mean of oil series after filling missing values with 0

oil.loc[:, 'dcoilwtico'].fillna(0).mean()

np.float64(65.32379310344828)

In [47]:
# calculate mean of oil series after filling missing values with the mean of oil price

oil.loc[:, 'dcoilwtico'].fillna(oil.loc[:, 'dcoilwtico'].mean()).mean()

np.float64(67.71436595744682)

### Filtering

In [48]:
oil.loc[oil["dcoilwtico"] > 100]
oil.loc[oil["date"].str[:4] == '2013']

           date  dcoilwtico
0    2013-01-01         NaN
1    2013-01-02       93.14
2    2013-01-03       92.97
3    2013-01-04       93.12
4    2013-01-07       93.20
..          ...         ...
256  2013-12-25         NaN
257  2013-12-26       99.18
258  2013-12-27       99.94
259  2013-12-30       98.90
260  2013-12-31       98.17

[261 rows x 2 columns]

### Query

In [49]:
my_var= 0
retails_df.query("family in ['AUTOMOTIVE'] and sales > @my_var")

              id        date  store_nbr      family  sales  onpromotion
561      1946505  2016-01-01         25  AUTOMOTIVE    4.0            0
1782     1947726  2016-01-02          1  AUTOMOTIVE    7.0            0
1815     1947759  2016-01-02         10  AUTOMOTIVE    1.0            0
1848     1947792  2016-01-02         11  AUTOMOTIVE   14.0            0
1881     1947825  2016-01-02         12  AUTOMOTIVE   16.0            0
...          ...         ...        ...         ...    ...          ...
1054779  3000723  2017-08-15         54  AUTOMOTIVE    8.0            0
1054812  3000756  2017-08-15          6  AUTOMOTIVE    7.0            0
1054845  3000789  2017-08-15          7  AUTOMOTIVE    5.0            0
1054878  3000822  2017-08-15          8  AUTOMOTIVE    4.0            0
1054911  3000855  2017-08-15          9  AUTOMOTIVE   15.0            0

[30208 rows x 6 columns]

# Assignment 6: Filtering DataFrames

I need some quick research on store 25:

* First, calculate the percentage of times ALL stores had more than 2000 transactions
* Then, calculate the percentage of times store 25 had more than 2000 transactions, and calculate the sum of transactions on these days
* Finally, sum the transactions for stores 25 and 3, that occurred in May or June, and had less than 2000 transactions

In [50]:
transactions.head()

         date  store_nbr  transactions
1  2013-01-02          1          2111
2  2013-01-02          2          2358
3  2013-01-02          3          3487
4  2013-01-02          4          1922
5  2013-01-02          5          1903

In [51]:
# all stores > 2500 percentage occurence

print ((transactions['transactions'] > 2000).mean())

0.266808006036868

In [52]:
# Number of times store 25 had > 2000 divided by total days for store 25 to get percent of time it happened

mask = (transactions['transactions'] > 2000) & (transactions['store_nbr'] == 25)

(transactions.loc[mask, 'transactions'].count() 
 / transactions.loc[(transactions['store_nbr'] == 25), 'transactions'].count())

np.float64(0.03469640644361834)

In [53]:
# Sum of transactions where store 25 had > 2000 transactions

transactions.loc[mask, 'transactions'].sum()

np.int64(144903)

In [54]:
# sum of transactions for stores 25 and 31 in months May and June on days they had less than 2000 transactions

(transactions.query(
    "store_nbr in [25, 31] & date.str[6] in ['5', '6'] & transactions < 2000")
 .loc[:, "transactions"]
 .sum())

np.int64(644910)

### Sorting by index

In [55]:
retails_df.sort_index(ascending=False) # Sort by rows by default (axis =0)
retails_df.sort_index(axis=1) # Sort by coulums
retails_df.sort_values # Sort by values
retails_df.sort_values(["store_nbr","family"] , ascending=[False,True] ) # Sort by values

              id        date  store_nbr      family   sales  onpromotion
1617     1947561  2016-01-01         54  AUTOMOTIVE   0.000            0
3399     1949343  2016-01-02         54  AUTOMOTIVE  14.000            0
5181     1951125  2016-01-03         54  AUTOMOTIVE   7.000            0
6963     1952907  2016-01-04         54  AUTOMOTIVE   5.000            1
8745     1954689  2016-01-05         54  AUTOMOTIVE   7.000            0
...          ...         ...        ...         ...     ...          ...
1046066  2992010  2017-08-11          1     SEAFOOD  19.424            4
1047848  2993792  2017-08-12          1     SEAFOOD  20.150            0
1049630  2995574  2017-08-13          1     SEAFOOD  11.378            0
1051412  2997356  2017-08-14          1     SEAFOOD  14.129            0
1053194  2999138  2017-08-15          1     SEAFOOD  22.487            0

[1054944 rows x 6 columns]

# Assignment 7: Sorting DataFrames

Hi there,
* Can you get me a dataset that includes the 5 days with the highest transactions counts? Any similarities between them?
* Then, can you get me a dataset sorted by date from earliest to most recent, but with the highest transactions first and the lowest transactions last for each day?
* Finally, sort the columns in reverse alphabetical order. 

Thanks!

In [56]:
transactions.head()

         date  store_nbr  transactions
1  2013-01-02          1          2111
2  2013-01-02          2          2358
3  2013-01-02          3          3487
4  2013-01-02          4          1922
5  2013-01-02          5          1903

In [57]:
# sort dataframe by values in transaction column in descending order (ascending = False)
# then grab first 5 rows to retrieve 5 highest days

transactions.sort_values('transactions', ascending=False).iloc[:5, :]

             date  store_nbr  transactions
52011  2015-12-23         44          8359
71010  2016-12-23         44          8307
16570  2013-12-23         44          8256
33700  2014-12-23         44          8120
16572  2013-12-23         46          8001

In [58]:
# Sort dataframe by date in ascending order, and trasactions in descending order

transactions.sort_values(['date', 'transactions'], ascending=[True, False])

             date  store_nbr  transactions
40     2013-01-02         46          4886
38     2013-01-02         44          4821
39     2013-01-02         45          4208
41     2013-01-02         47          4161
11     2013-01-02         11          3547
...           ...        ...           ...
83455  2017-08-15         22           766
83449  2017-08-15         16           742
83465  2017-08-15         32           615
83468  2017-08-15         35           612
83459  2017-08-15         26           534

[83487 rows x 3 columns]

In [59]:
# sort columns in reverse alphabetical order using sort_index on the column axis (1), in descending order

transactions.sort_index(axis=1, ascending=False)

       transactions  store_nbr        date
1              2111          1  2013-01-02
2              2358          2  2013-01-02
3              3487          3  2013-01-02
4              1922          4  2013-01-02
5              1903          5  2013-01-02
...             ...        ...         ...
83483          2804         50  2017-08-15
83484          1573         51  2017-08-15
83485          2255         52  2017-08-15
83486           932         53  2017-08-15
83487           802         54  2017-08-15

[83487 rows x 3 columns]

In [60]:
product_df.columns

Index(['PRODUCT_ID', 'MANUFACTURER', 'DEPARTMENT', 'BRAND', 'COMMODITY_DESC',
       'SUB_COMMODITY_DESC', 'CURR_SIZE_OF_PRODUCT'],
      dtype='str')

In [63]:
product_df.columns= [col.lower() for col in product_df.columns ]
product_df.columns

Index(['product_id', 'manufacturer', 'department', 'brand', 'commodity_desc',
       'sub_commodity_desc', 'curr_size_of_product'],
      dtype='str')

In [64]:
# 2nd way to rename
path = "../project_data/product.csv"

# read in trasactions csv and create DataFrame
product_df = pd.read_csv(path)
product_df = product_df.rename(columns={
    'product_id': 'product_id'
})

# Assignment 8: Modifying Columns

Just some quick work, but can you send me the transaction data with the columns renamed?

* Rename `transactions` to `transaction_count` and `store_nbr` to `store_number`.
* Reorder the columns so date is first, then store number, then transaction count.

Thanks!

In [65]:
transactions.head()

         date  store_nbr  transactions
1  2013-01-02          1          2111
2  2013-01-02          2          2358
3  2013-01-02          3          3487
4  2013-01-02          4          1922
5  2013-01-02          5          1903

In [66]:
# Use rename to change column names
# Use reindex, axis=1, to reorder columns (this can also be done by assignment FYI)

transactions =(transactions
 .rename(
    columns={"transactions": "transaction_count", "store_nbr": "store_number"})
 .reindex(labels=["date", "transaction_count", "store_number"], axis=1)
)

transactions.head()

         date  transaction_count  store_number
1  2013-01-02               2111             1
2  2013-01-02               2358             2
3  2013-01-02               3487             3
4  2013-01-02               1922             4
5  2013-01-02               1903             5

### Column Creation

In [70]:
transactions["total"] = transactions["transaction_count"] + transactions["store_number"]
transactions["total_boolean"] = transactions["transaction_count"] != transactions["store_number"]

transactions

             date  transaction_count  store_number  total  total_boolean
1      2013-01-02               2111             1   2112           True
2      2013-01-02               2358             2   2360           True
3      2013-01-02               3487             3   3490           True
4      2013-01-02               1922             4   1926           True
5      2013-01-02               1903             5   1908           True
...           ...                ...           ...    ...            ...
83483  2017-08-15               2804            50   2854           True
83484  2017-08-15               1573            51   1624           True
83485  2017-08-15               2255            52   2307           True
83486  2017-08-15                932            53    985           True
83487  2017-08-15                802            54    856           True

[83487 rows x 5 columns]

# Assignment 9: Column Creation

Just some quick work, but can you send me the transaction data with the columns renamed?

* Create a `pct_to_target` column that divides transactions by 2500.
* Then, create a `met_target` column that returns True if `pct_to_target` is greater than or equal to 1.
* Next, create a `bonus_payable` column that equals 100 if `met_target` is True, and 0 if not. Then sum the bonus payable column.
* Finally, create columns for month and day of week as integers. There is some helper code for these dateparts below.



Thanks!

In [36]:
transactions.head()

         date  transaction_count  store_number
1  2013-01-02               2111             1
2  2013-01-02               2358             2
3  2013-01-02               3487             3
4  2013-01-02               1922             4
5  2013-01-02               1903             5

In [37]:
# target based columns
transactions["pct_to_target"] = transactions.loc[:, "transaction_count"] / 2500
transactions["met_target"] = transactions.loc[:, "pct_to_target"] >= 1
transactions["bonus_payable"] = 100 * transactions["met_target"]

# Date Columns
transactions["date"] = transactions["date"].astype("Datetime64")
transactions["month"] = transactions["date"].dt.month
transactions["day_of_week"] = transactions["date"].dt.dayofweek

transactions.head()

,date,transaction_count,store_number,pct_to_target,met_target,bonus_payable,month,day_of_week
1,2013-01-02,2111,1,0.8444,False,0,1,2
2,2013-01-02,2358,2,0.9432,False,0,1,2
3,2013-01-02,3487,3,1.3948,True,100,1,2
4,2013-01-02,1922,4,0.7688,False,0,1,2
5,2013-01-02,1903,5,0.7612,False,0,1,2

In [38]:
# Call sum on "bonus_payable" column to get total sum of bonus paid

transactions.loc[:, "bonus_payable"].sum()

1448300

# Assignment 10: np.select

Hi there! I need a few columns created.

1. Create a ‘seasonal_bonus’ column that applies to these dates: 
    * All days in December (month = 12)
    * Sundays (day_of_week = 6) in May (month = 5)
    * Mondays (day_of_week = 0) in July (month = 7)
2. Call the December bonus ‘Holiday Bonus’, the May bonus ‘Corporate Month’, and the July bonus ‘Summer Special’. If no bonus applies, the column should display ‘None’. 
3. Finally, calculate the total bonus owed at $100 per day.

Thanks!

In [39]:
transactions.head()

,date,transaction_count,store_number,pct_to_target,met_target,bonus_payable,month,day_of_week
1,2013-01-02,2111,1,0.8444,False,0,1,2
2,2013-01-02,2358,2,0.9432,False,0,1,2
3,2013-01-02,3487,3,1.3948,True,100,1,2
4,2013-01-02,1922,4,0.7688,False,0,1,2
5,2013-01-02,1903,5,0.7612,False,0,1,2

In [40]:
# set up the three conditions
conditions = [
    transactions["month"] == 12,
    (transactions["month"] == 5) & (transactions["day_of_week"] == 6),
    (transactions["month"] == 7) & (transactions["day_of_week"] == 0)
]

# specify outcomes for each condition
choices = ["Holiday Bonus", "Corporate Month", "Summer Special"]

# Call the select method, passing in conditions, choices, and a default value of 'None' if no condition met
transactions["seasonal_bonus"] = np.select(conditions, choices, default="None")

transactions.head()

,date,transaction_count,store_number,pct_to_target,met_target,bonus_payable,month,day_of_week,seasonal_bonus
1,2013-01-02,2111,1,0.8444,False,0,1,2,None
2,2013-01-02,2358,2,0.9432,False,0,1,2,None
3,2013-01-02,3487,3,1.3948,True,100,1,2,None
4,2013-01-02,1922,4,0.7688,False,0,1,2,None
5,2013-01-02,1903,5,0.7612,False,0,1,2,None

In [41]:
# look at frequency for each 
transactions["seasonal_bonus"].value_counts()

None               75258
Holiday Bonus       6028
Summer Special      1103
Corporate Month     1098
Name: seasonal_bonus, dtype: int64

In [42]:
# Use value counts to extract counts of each holiday, 
# slice the series returned by value counts, and sum relevant values before multiply by 100 to get bonus owed

transactions.loc[:, "seasonal_bonus"].value_counts().iloc[1:].sum() * 100

822900

# Assignment 11: Assign 

* Drop the columns that have been created so far (keep only date, store_number, and transaction count), and recreate them using the assign method.
* Then sum the seasonal bonus owed once again to make sure the numbers are correct.

In [43]:
# Drop columns we created in prior exercises
transactions = transactions.drop(
    [
        "pct_to_target",
        "met_target",
        "bonus_payable",
        "month",
        "day_of_week",
        "seasonal_bonus",
    ],
    axis=1,
)

transactions.head()

        date  transaction_count  store_number
1 2013-01-02               2111             1
2 2013-01-02               2358             2
3 2013-01-02               3487             3
4 2013-01-02               1922             4
5 2013-01-02               1903             5

In [44]:
# Create same columns with assign

transactions = transactions.assign(
    target_pct = transactions["transaction_count"] / 2500,
    met_target = (transactions["transaction_count"] / 2500) >= 1,
    bonus_payable = ((transactions["transaction_count"] / 2500) >= 1) * 100,
    month = transactions.date.dt.month,
    day_of_week = transactions.date.dt.dayofweek,
    seasonal_bonus = np.select(conditions, choices, default="None"),
)

In [45]:
# Same method as assignment 10

transactions.loc[:, "seasonal_bonus"].value_counts().iloc[1:].sum() * 100

822900

# Assignment 12: Memory Optimization

Reduce the memory usage of the transactions DataFrame to below 5MB.

In [46]:
transactions.head()

,date,transaction_count,store_number,target_pct,met_target,bonus_payable,month,day_of_week,seasonal_bonus
1,2013-01-02,2111,1,0.8444,False,0,1,2,None
2,2013-01-02,2358,2,0.9432,False,0,1,2,None
3,2013-01-02,3487,3,1.3948,True,100,1,2,None
4,2013-01-02,1922,4,0.7688,False,0,1,2,None
5,2013-01-02,1903,5,0.7612,False,0,1,2,None

In [71]:
transactions.info(memory_usage="deep")

<class 'pandas.DataFrame'>
RangeIndex: 83487 entries, 1 to 83487
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   date               83487 non-null  str
 1   transaction_count  83487 non-null  int64
 2   store_number       83487 non-null  int64
 3   total              83487 non-null  int64
 4   total_boolean      83487 non-null  bool
dtypes: bool(1), int64(3), str(1)
memory usage: 7.3 MB

In [48]:
# Note - you may have been more conservative here, and that's OK.
# The main point is reducing memory consumption. Playing it safe is often wise.

transactions = transactions.astype(
    {
        "store_number": "Int8",
        "transaction_count": "Int16",
        "bonus_payable": "Int8",
        "month": "Int8",
        "day_of_week": "Int8",
        "seasonal_bonus": "category",
    }
)

In [49]:
transactions.head()

,date,transaction_count,store_number,target_pct,met_target,bonus_payable,month,day_of_week,seasonal_bonus
1,2013-01-02,2111,1,0.8444,False,0,1,2,None
2,2013-01-02,2358,2,0.9432,False,0,1,2,None
3,2013-01-02,3487,3,1.3948,True,100,1,2,None
4,2013-01-02,1922,4,0.7688,False,0,1,2,None
5,2013-01-02,1903,5,0.7612,False,0,1,2,None

In [50]:
# down to 2.9MB vs. 10.1 to start. Will work on Chandler's grandparents computer!

transactions.info(memory_usage="deep")

<class 'pandas.core.frame.DataFrame'>
Int64Index: 83487 entries, 1 to 83487
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   date               83487 non-null  datetime64[ns]
 1   transaction_count  83487 non-null  Int16
 2   store_number       83487 non-null  Int8
 3   target_pct         83487 non-null  float64
 4   met_target         83487 non-null  bool
 5   bonus_payable      83487 non-null  Int8
 6   month              83487 non-null  Int8
 7   day_of_week        83487 non-null  Int8
 8   seasonal_bonus     83487 non-null  category
dtypes: Int16(1), Int8(4), bool(1), category(1), datetime64[ns](1), float64(1)
memory usage: 2.9 MB